### ISSUE TITLE
如何设置组件高度为100%？

### ISSUE THREAD

**Issue by sudor** [dirkliu/vue-json-editor#12]
我尝试将 style="height: 100%", 但是好像没有作用？在开发者控制台调试，需要同时将.jsoneditor-vue这个样式的控件高度调成100%才行，我的代码如下：

<vue-json-editor v-model="json" mode="code" :showBtns="false" @json-change="onJsonChange" style="height: 100%"></vue-json-editor>

**Comment by jxttian** [comment]
兄台  最后有解决吗？

**Comment by kajweb** [comment]
直接设置好像可以
```
<style  lang="less">
.jsoneditor-vue{
    height: 100%;
}
```

**Comment by nickyang86** [comment]
首先设置高度：
<vue-json-editor style="height: 450px"></vue-json-editor>

然后修改默认样式：
<style>
  .jsoneditor-vue {
    height: 100%;
  }
</style>
注意，style标签里面不能有scoped，否则无法生效
