### ISSUE TITLE
lang mode modes 不设置的话vue会报不能修改的错误

### ISSUE THREAD

**Issue by 2015308200114dujiawei** [dirkliu/vue-json-editor#25]
error:
vue.esm.js?a026:591 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "modes"
原因是：源码中当不传入lang mode modes时会走：
            if (this.mode === undefined) this.mode = defaultMode;
            if (this.modes === undefined) this.modes = defaultModes;
            if (this.lang === undefined) this.lang = 'en';这个逻辑
这样会修改prop从而报错，
建议默认值采用    lang {
      type: String,
      default: 'en'
    },这种方式设定默认值，从而避免报错

**Comment by danielclariondoor** [comment]
same for me

**Comment by 2015308200114dujiawei** [comment]
> same for me

use https://github.com/2015308200114dujiawei/better-vue-json-editor

**Comment by dirkliu** [comment]
> error:
> vue.esm.js?a026:591 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "modes"
> 原因是：源码中当不传入lang mode modes时会走：
> if (this.mode === undefined) this.mode = defaultMode;
> if (this.modes === undefined) this.modes = defaultModes;
> if (this.lang === undefined) this.lang = 'en';这个逻辑
> 这样会修改prop从而报错，
> 建议默认值采用 lang {
> type: String,
> default: 'en'
> },这种方式设定默认值，从而避免报错

tks, 已经修复了
