### ISSUE TITLE
code模型下，怎么调整编辑器的高度呢

### ISSUE THREAD

**Issue by xiazhibin** [dirkliu/vue-json-editor#33]
code模型下，怎么调整编辑器的高度呢

**Comment by edfeff** [comment]
同问。

**Comment by saltedFish5** [comment]
[https://www.cnblogs.com/tanweiwei/p/13043125.html](url)
参考上面网址有答案
/deep/.jsoneditor-vue{
    height:500px;
  }
  /deep/.json-save-btn{
    margin-top: 10px;
    cursor: pointer;
    width: 100px;
    line-height: 30px;
    font-size: 14px;
  }

**Comment by saltedFish5** [comment]
你们编辑中文时，有没有遇到重影的问题是怎么解决的？

**Comment by godcrazytoo** [comment]
> [https://www.cnblogs.com/tanweiwei/p/13043125.html](url)
> 参考上面网址有答案
> /deep/.jsoneditor-vue{
> height:500px;
> }
> /deep/.json-save-btn{
> margin-top: 10px;
> cursor: pointer;
> width: 100px;
> line-height: 30px;
> font-size: 14px;
> }

请教下code模式下怎么设置让编辑框的高度随着内容的变化而变化呢？
