### ISSUE TITLE
The svg icons not working

### ISSUE THREAD

**Issue by beatrizsmerino** [dirkliu/vue-json-editor#49]
![image](https://user-images.githubusercontent.com/14045148/145641000-550a218d-51c6-4a3f-a19b-392df74e819e.png)
![image](https://user-images.githubusercontent.com/14045148/145641203-19482a88-4846-46cf-a6f7-0ed1a89e5fc9.png)
![image](https://user-images.githubusercontent.com/14045148/145648068-25323a85-738e-4932-b46b-41cd3801a938.png)

[https://codesandbox.io/s/tender-poincare-1w70r](https://codesandbox.io/s/tender-poincare-1w70r)

**Comment by Eddie344** [comment]
Same problem, there is wrong url of svg file
![image](https://user-images.githubusercontent.com/53879350/146759148-9984eb09-4793-4e1e-a081-936017696f9d.png)

**Comment by beatrizsmerino** [comment]
I'm using `vue-json-editor` together with `svg-symbol-sprite-loader` package.
I have managed to make it work, with these settings in the `vue.config.js` file.

I hope it helps

```javascript
const path = require('path');
const SVGSymbolSprite = require('svg-symbol-sprite-loader');

// Define the resolve method to obtain the absolute path of the file
const resolve = dir => path.join(__dirname, dir);

module.exports = {
	// A function that recives a ChainableConfig instance based on webpack chain
	// Allows more fine-grained modifications to the internal webpack configuration
	chainWebpack: config => {
		// Create and insert sprite before the html body
		config.plugin('svg-symbol-sprite-loader').after('html').
			use(SVGSymbolSprite.Plugin).
			end();

		// Configure svg default rultes to exclude svg file proccessing in icons directory
		config.module.
			rule('svg').
			exclude.add(resolve('src/assets/images/icons/svg')).
			end();

		// New icons rule, set svg sprite loader to process svg files in the 'src/assets/images/icons/svg' folder
		config.module.
			rule('svg-sprite').
			uses.clear().
			end().
			test(/\.svg$/u).
			include.add(resolve('src/assets/images/icons/svg')).
			end().
			use('svg-symbol-sprite-loader').
			loader('svg-symbol-sprite-loader').
			options({
				symbolId: filePath => `icon-${path.basename(filePath, '.svg')}`
			}).
			end();

	}
};
```

**Comment by beatrizsmerino** [comment]
Hi! @Eddie344

I have created a simple repo to test the `vue-json-editor` package

![vue-editor](https://user-images.githubusercontent.com/14045148/147427760-4592205b-8d25-413c-b50e-23f5168b341c.png)
[https://beatrizsmerino.github.io/vue-editor/](https://beatrizsmerino.github.io/vue-editor/)
